tasks:
  - name : FlaskWebServer
    init: cd flask && pip install -r requirements.txt && npm i -g nodemon && nodemon app.py # runs during prebuild
  - name : AngWebServer
    init: cd ev_stations && npm i -g @angular/cli && npm i && ng serve --disable-host-check # runs during prebuild

# List the ports to expose. Learn more https://www.gitpod.io/docs/config-ports/
ports:
  - port: 4200
    onOpen: open-browser
    visibility : public 
  - port: 5000
    visibility : public 
